{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dCalendario\",\"dw dAgenteAgidesk\",\"dw dClienteAgidesk\",\"dw dProjetoAgidesk\",\"dw dQuadroAgidesk\",\"dw dTarefaAgidesk\",\"dw dJunkLancamentosAgidesk\",\"dw fLancamentosAgidesk\",\"Dados do Relatório\",\"Medidas\",\"PlanejamentoAlocacao\",\"HorasProjetos\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.1126.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Dimensões"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Fatos"
      }
    ],
    "relationships": [
      {
        "name": "d8a73805-29f7-43f9-9b0e-1eaea8e806f3",
        "fromColumn": "_SK Cliente Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Cliente Agidesk",
        "toTable": "dw dClienteAgidesk"
      },
      {
        "name": "493cac68-7ead-4b48-bc5d-b35659532c0a",
        "fromColumn": "_SK Junk Lançamentos Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Junk Lançamentos Agidesk",
        "toTable": "dw dJunkLancamentosAgidesk"
      },
      {
        "name": "bf87e5e2-41bd-4266-bcb3-c86179d55161",
        "fromColumn": "_SK Projeto Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Projeto Agidesk",
        "toTable": "dw dProjetoAgidesk"
      },
      {
        "name": "1e61bcc3-79f6-4334-a535-bf368d1f1406",
        "fromColumn": "_SK Tarefa Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Tarefa Agidesk",
        "toTable": "dw dTarefaAgidesk"
      },
      {
        "name": "ca14bc08-a7a2-4ea4-9b4c-a4749c08ebdd",
        "fromColumn": "_SK Agente Operador Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Agente Agidesk",
        "toTable": "dw dAgenteAgidesk"
      },
      {
        "name": "8b25f148-0f5f-4c6f-a22d-fe3099b1d4ab",
        "fromColumn": "Data Lançamento Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "Data",
        "toTable": "dCalendario"
      },
      {
        "name": "6b05bf1f-2821-4722-8081-502924c267ce",
        "fromColumn": "_SK Quadro Agidesk",
        "fromTable": "dw fLancamentosAgidesk",
        "toColumn": "_SK Quadro Agidesk",
        "toTable": "dw dQuadroAgidesk"
      },
      {
        "name": "5ca11162-9fc8-d390-522e-4a73c8e7b463",
        "fromColumn": "Cliente",
        "fromTable": "HorasProjetos",
        "toColumn": "_BK Cliente Agidesk",
        "toTable": "dw dClienteAgidesk"
      },
      {
        "name": "bb6a1c78-f9cf-bc6c-dbf3-e8bb3e61fe78",
        "fromColumn": "Projeto",
        "fromTable": "HorasProjetos",
        "toColumn": "_BK Projeto Agidesk",
        "toTable": "dw dProjetoAgidesk"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dw dAgenteAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_SK Agente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f29f251e-dc0b-47cc-a36b-26cb62b77194",
            "sourceColumn": "_SK Agente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_BK Agente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5576a8d-9c9b-42da-ac35-b523177f8c31",
            "sourceColumn": "_BK Agente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Analista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93d9ed13-54ae-4edc-9070-23f3062b2176",
            "sourceColumn": "Analista",
            "summarizeBy": "none"
          },
          {
            "name": "FotoAnalista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH('dw dAgenteAgidesk'[_BK Agente Agidesk], ",
              "    \"Alexandre | Row Up\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlwAAAJYCAYAAAC3jTimAAAKN2lDQ1BzUkdCIElF\", ",
              "    \"Lucas | Row Up\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAk4AAAJYCAYAAACU1mlzAAAKN2lDQ1BzUkdCIElF\",",
              "    \"Talita | Row Up\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlIAAAJYCAYAAACpRAgVAAAKN2lDQ1BzUkdCIElF\",",
              "    \"Bruno | Row Up\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAmgAAAJYCAYAAADWlRrkAAAAAXNSR0IArs4c6QAA\",",
              "    \"Felipe | Row Up\", \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAm4AAAJYCAYAAADbi2qjAAAAAXNSR0IArs4c6QAA\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "eeeac560-a76f-4460-8649-f7dff136e6ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Nome Agente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7c8c1fb-7531-4d7d-9ee0-b7ba453cb0e9",
            "sourceColumn": "Nome Agente Agidesk",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ee148cf-dde4-4da1-aed8-93a4c574b3df",
        "partitions": [
          {
            "name": "dw dAgenteAgidesk-614d17f4-5bdd-420d-883e-814001ed6df3",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"SRV3HLDBS02\\PRODUCAO\"),",
                "    DWBI = Fonte{[Name=\"DWBI\"]}[Data],",
                "    dw_dAgenteAgidesk = DWBI{[Schema=\"dw\",Item=\"dAgenteAgidesk\"]}[Data],",
                "    Personalizar1 = Table.AddColumn(dw_dAgenteAgidesk, \"Texto Antes do Delimitador\", each Text.BeforeDelimiter([_BK Agente Agidesk], \"|\"), type text),",
                "    Personalizar2 = Table.RenameColumns(#\"Personalizar1\",{{\"Texto Antes do Delimitador\", \"Analista\"}})",
                "in",
                "    Personalizar2"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw dClienteAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_BK Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47d14303-92a8-4ff4-9523-b0f4f06b2870",
            "sourceColumn": "_BK Cliente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a551281-4872-4966-b11b-bcf903b3f295",
            "sourceColumn": "Descrição Cliente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c492b9d-49ab-4866-ae68-f21567d0036d",
            "sourceColumn": "_SK Cliente Agidesk",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0bebe636-f525-44c2-b366-c2739e9f55ce",
        "partitions": [
          {
            "name": "dw dClienteAgidesk-caeb2513-62e1-4b8c-95a7-d0563e62ef9b",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"SRV3HLDBS02\\PRODUCAO\"),",
                "    DWBI = Fonte{[Name=\"DWBI\"]}[Data],",
                "    dw_dClienteAgidesk = DWBI{[Schema=\"dw\",Item=\"dClienteAgidesk\"]}[Data]",
                "in",
                "    dw_dClienteAgidesk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw dJunkLancamentosAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_SK Junk Lançamentos Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "647f3cc5-2d27-47be-9992-a97cb6a8ea01",
            "sourceColumn": "_SK Junk Lançamentos Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_BK Junk Lançamentos Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5453e999-eff8-4e6e-b7a0-efd9ce17d00d",
            "sourceColumn": "_BK Junk Lançamentos Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Faturamento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97fb58b9-4f27-4b1c-9851-46fa8b5cdcb6",
            "sourceColumn": "Tipo Faturamento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Status Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11fd3986-332a-4988-8de5-3c09f66fb444",
            "sourceColumn": "Status Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Time Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b82416f0-9542-45ea-9863-3c91cdda8f74",
            "sourceColumn": "Time Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Lançamento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7a30d17-74ae-4945-be77-dbbc7b2b7b22",
            "sourceColumn": "Tipo Lançamento Agidesk",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6be821cc-089c-4c7a-96f3-bb569f6b576d",
        "partitions": [
          {
            "name": "dw dJunkLancamentosAgidesk-e9d09eeb-f6f2-4200-8be9-0259982f7bbf",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"SRV3HLDBS02\\PRODUCAO\", \"DWBI\"),",
                "    dw_dJunkLancamentosAgidesk = Fonte{[Schema=\"dw\",Item=\"dJunkLancamentosAgidesk\"]}[Data]",
                "in",
                "    dw_dJunkLancamentosAgidesk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw dProjetoAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "_SK Projeto Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d71db609-e191-40ef-8c66-bc518c9e3fc1",
            "sourceColumn": "_SK Projeto Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_BK Projeto Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7125733d-e902-4a8d-8635-385acb55297c",
            "sourceColumn": "_BK Projeto Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Projeto Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99a75dd8-2f74-45ee-b999-8d030abd9705",
            "sourceColumn": "Nome Projeto Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d04d74b5-54f4-4b45-b4b9-6aeec96973c0",
            "sourceColumn": "Cliente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Horas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "690fdf1d-a1bd-4732-bed5-3096f0d9f485",
            "sourceColumn": "Horas",
            "summarizeBy": "sum"
          },
          {
            "name": "Recorrêcia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34825fcf-7e94-42e6-98ee-5baf47b304de",
            "sourceColumn": "Recorrêcia",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd3b17b1-ec46-4d9a-96ec-b30ea7da5512",
        "partitions": [
          {
            "name": "dw dProjetoAgidesk-d6587c92-e4a1-4262-9a67-a8097af56827",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"SRV3HLDBS02\\PRODUCAO\"),",
                "    DWBI = Fonte{[Name=\"DWBI\"]}[Data],",
                "    dw_dProjetoAgidesk = DWBI{[Schema=\"dw\",Item=\"dProjetoAgidesk\"]}[Data],",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(dw_dProjetoAgidesk, {\"_BK Projeto Agidesk\"}, HorasProjetos, {\"Projeto\"}, \"HorasProjetos\", JoinKind.LeftOuter),",
                "    #\"HorasProjetos Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"HorasProjetos\", {\"Horas\", \"Recorrêcia\"}, {\"Horas\", \"Recorrêcia\"})",
                "in",
                "    #\"HorasProjetos Expandido\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw dTarefaAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_SK Tarefa Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9b685c68-957f-4210-9b21-477a8bb5b2b3",
            "sourceColumn": "_SK Tarefa Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_BK Tarefa Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "144d3a2c-b134-41ea-aec4-1b84930cb745",
            "sourceColumn": "_BK Tarefa Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Título Tarefa Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64be2f11-20ab-46fc-bb1d-9bc7689b4a00",
            "sourceColumn": "Título Tarefa Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Link Tarefa Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3b79832-faa9-43e1-a593-d8b9fdcef74b",
            "sourceColumn": "Link Tarefa Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Tarefa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "[_BK Tarefa Agidesk] & \" - \" & [Título Tarefa Agidesk]",
            "isDataTypeInferred": true,
            "lineageTag": "b552080a-0a78-4fcc-9523-29655dc090f1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "6449e7ea-3d23-429f-a626-3250ccd9db93",
        "partitions": [
          {
            "name": "dw dTarefaAgidesk-108f515b-05e4-4ecb-9e61-f62857f18993",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"SRV3HLDBS02\\PRODUCAO\"),",
                "    DWBI = Fonte{[Name=\"DWBI\"]}[Data],",
                "    dw_dTarefaAgidesk = DWBI{[Schema=\"dw\",Item=\"dTarefaAgidesk\"]}[Data]",
                "in",
                "    dw_dTarefaAgidesk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "f178a88b-4ae9-43dd-beee-640ef3dd81fd",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f58d5046-ff79-422a-9a5f-be9f1f22c360",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "38899e57-5187-4cd6-8f87-fe9c0d3febda",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c35d513b-e7b4-4c47-ba21-343887315018",
            "sourceColumn": "Dia",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "595cd288-27aa-4d7f-90d4-6739f4e0e042",
            "sourceColumn": "Semestre",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ac8c826-d279-4427-a110-873306cbb0c6",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16d56393-95a1-4b63-89fc-f7546d886aa1",
            "sourceColumn": "Dia Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Semana Texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd26a611-e3ac-48a9-b3e1-ba164770462e",
            "sourceColumn": "Dia Semana Texto",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Semana Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2e8dd87-b90c-4698-b68f-78597df46551",
            "sortByColumn": "Dia Semana",
            "sourceColumn": "Dia Semana Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d1121e5-74cc-49e3-98d8-3d56a8394e76",
            "sourceColumn": "Mês Texto",
            "summarizeBy": "none"
          },
          {
            "name": "Mes Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9150ce3-c686-42ea-95f4-25832b810a8c",
            "sourceColumn": "Mes Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre Sigla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3996066e-30e8-44d1-9c9c-65b3dc953e7b",
            "sourceColumn": "Trimestre Sigla",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e08ec0bf-4bfd-4d68-be13-bf503c4f16d6",
            "sourceColumn": "Trimestre Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre Texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc70eb85-9e32-4104-81ab-ab4653eeebee",
            "sourceColumn": "Trimestre Texto",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre Sigla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "422474c5-b395-499a-9fcc-db07b197150b",
            "sourceColumn": "Semestre Sigla",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ec517ac-17e7-4ea9-bfeb-1e46f053abbf",
            "sourceColumn": "Semestre Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre Texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5e74101-43e8-4d1d-aed8-b8e79202aa1d",
            "sourceColumn": "Semestre Texto",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fcd850c2-6b0e-43f6-9a11-a2ff4c3a543d",
            "sourceColumn": "Semana Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Ano Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bd0ebd0-af4e-4dff-9708-9b0eda53dba5",
            "sourceColumn": "Semana Ano Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6cbb344-408c-4e8d-86ce-6abc119b2b22",
            "sourceColumn": "Semana Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Mês Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19f12ea6-5201-4c8b-be44-2d70d499fd0b",
            "sourceColumn": "Semana Mês Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Útil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d1b8829-338b-43ad-8855-228994ead7ac",
            "sourceColumn": "Dia Útil",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Úteis Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a07b562-89a9-482e-9375-ab4eb26d1a25",
            "sourceColumn": "Dias Úteis Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Não Úteis Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "818e1716-1a63-468f-9c0b-4922342b63cc",
            "sourceColumn": "Dias Não Úteis Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Úteis Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b80d8b3-9a67-4080-83b4-d3916e0d35f0",
            "sourceColumn": "Dias Úteis Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Não Úteis Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2598f9ef-8c63-431e-b49a-f68db78d37ba",
            "sourceColumn": "Dias Não Úteis Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Úteis Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0125855-7ba3-4a72-9d1c-3472a0650ae3",
            "sourceColumn": "Dias Úteis Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Não Úteis Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e735f34b-c3d3-431d-82f9-778ae08e0db8",
            "sourceColumn": "Dias Não Úteis Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Dias Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17b804b7-8e90-4f75-b61f-e13833a41f97",
            "sourceColumn": "Dias Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Primeiro Dia Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "39291651-fa04-433b-bd4e-f79813dec907",
            "sourceColumn": "Primeiro Dia Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Último Dia Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "751967b5-a7f9-4d86-a73e-f16352212961",
            "sourceColumn": "Último Dia Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Primeiro Dia Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "ae81c7b7-0c04-4f6c-b781-93a0fc4bf410",
            "sourceColumn": "Primeiro Dia Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Último Dia Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f1bc0e45-e77f-4316-a105-d56cada3c418",
            "sourceColumn": "Último Dia Semana",
            "summarizeBy": "none"
          },
          {
            "name": "Data Referência Produtiva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "dec3bb4a-25c6-4f6d-9281-2be0bf89f31e",
            "sourceColumn": "Data Referência Produtiva",
            "summarizeBy": "none"
          },
          {
            "name": "Data Início Ciclo Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "818d6fba-1a75-4f98-ac20-7d682d759b2a",
            "sourceColumn": "Data Início Ciclo Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Data Fim Ciclo Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f2660152-6907-44b8-b014-13db521e5997",
            "sourceColumn": "Data Fim Ciclo Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Ciclo Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ecefa1db-9623-4dcf-9dbc-a54edff0bc3e",
            "sourceColumn": "Dia Ciclo Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Ano Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f472744f-1cfa-4f3a-b14a-bfaad7ed3105",
            "sourceColumn": "Dia Ano Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Produtiva Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f19fba54-6c9c-4a92-a8a0-f3268a284b24",
            "sourceColumn": "Semana Produtiva Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Semana Produtiva Mês Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5c6a6c3-e837-4464-843c-985a0a3261fc",
            "sourceColumn": "Semana Produtiva Mês Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16606f19-771d-4a54-a792-2a0364af224f",
            "sourceColumn": "Mês Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Produtivo Texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9436a95c-3fa5-42f2-94f4-41b0b3728479",
            "sourceColumn": "Mês Produtivo Texto",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Produtivo Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "37360dd0-3073-4b9f-b8f3-e5fa3b1a0c98",
            "sortByColumn": "Mês Produtivo",
            "sourceColumn": "Mês Produtivo Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Ano Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b62d67da-e057-4943-901e-74bcfe2bc53a",
            "sourceColumn": "Ano Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Ciclo Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ac1fd08-1bea-4df3-b98c-5fada2233556",
            "sortByColumn": "Ciclo Produtivo Numérico",
            "sourceColumn": "Ciclo Produtivo",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17a7633c-7cab-4f30-9fae-f530abc91a95",
            "sourceColumn": "Mês Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Ano Abreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32dcde75-9547-4761-9ea9-6ce91189b99f",
            "sourceColumn": "Ano Abreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Ciclo Produtivo Numérico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "066da98f-47d8-46a5-913c-55d8818bdbeb",
            "sourceColumn": "Ciclo Produtivo Numérico",
            "summarizeBy": "none"
          },
          {
            "name": "Ciclo Produtivo Seleção",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "614da496-69b9-4c8d-844b-230de4b1e597",
            "sortByColumn": "Ciclo Produtivo Numérico",
            "sourceColumn": "Ciclo Produtivo Seleção",
            "summarizeBy": "none"
          },
          {
            "name": "Posição Ciclo Produtivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e57acfd-6731-48e4-ad09-c9a4fd6ca074",
            "sourceColumn": "Posição Ciclo Produtivo",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "f40319a0-ddb8-4af2-bdcb-7cb97e46f81f",
        "partitions": [
          {
            "name": "dCalendario-89f5c8d0-f912-4417-931d-5628467561fd",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"SRV3HLDBS02\\PRODUCAO\"),",
                "    DWBI = Fonte{[Name=\"DWBI\"]}[Data],",
                "    dCalendario = DWBI{[Schema=\"dw\",Item=\"dCalendario\"]}[Data],",
                "    #\"Personalização Adicionada\" = Table.AddColumn(dCalendario, \"Ciclo Produtivo Numérico\", each Text.Range([Ciclo Produtivo],3,4) & Text.Range([Ciclo Produtivo],0,2)),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Data\", type date}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Tipo Alterado1\",{{\"Ciclo Produtivo Numérico\", Int64.Type}, {\"Primeiro Dia Mês\", type date}, {\"Último Dia Mês\", type date}, {\"Primeiro Dia Semana\", type date}, {\"Último Dia Semana\", type date}, {\"Data Referência Produtiva\", type date}, {\"Data Início Ciclo Produtivo\", type date}, {\"Data Fim Ciclo Produtivo\", type date}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Tipo Alterado\", \"Ciclo Produtivo Seleção\", each if Date.From(DateTime.LocalNow()) >= [Data Início Ciclo Produtivo] and Date.From(DateTime.LocalNow()) <= [Data Fim Ciclo Produtivo] ",
                "then \"Ciclo Atual\" ",
                "else if Date.AddMonths(Date.From(DateTime.LocalNow()),-1) >= [Data Início Ciclo Produtivo] and Date.AddMonths(Date.From(DateTime.LocalNow()),-1) <= [Data Fim Ciclo Produtivo]",
                "then \"Ciclo Anterior\" ",
                "else [Ciclo Produtivo]),",
                "    #\"Personalização Adicionada2\" = Table.AddColumn(#\"Personalização Adicionada1\", \"Posição Ciclo Produtivo\", each if [Ciclo Produtivo Seleção] = \"Ciclo Atual\"",
                "then \"Presente\"",
                "else if [Data] < Date.From(DateTime.LocalNow()) ",
                "then \"Passado\"",
                "else \"Futuro\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada2\",{{\"Ciclo Produtivo Seleção\", type text}, {\"Posição Ciclo Produtivo\", type text}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw fLancamentosAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_SK Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c448778c-1e08-47a0-9992-e4d5949228c2",
            "sourceColumn": "_SK Cliente",
            "summarizeBy": "sum"
          },
          {
            "name": "_SK Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "827e75bf-0066-488e-a325-60cdffee46ad",
            "sourceColumn": "_SK Cliente Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Projeto Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "428b5d8c-0f81-4182-ac14-807171b3b5ae",
            "sourceColumn": "_SK Projeto Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Quadro Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a97ad622-3308-4c5c-a3f6-f9be9da6d9b2",
            "sourceColumn": "_SK Quadro Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Agente Operador Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62fb0282-1a2f-452a-b22d-1a30d674cf15",
            "sourceColumn": "_SK Agente Operador Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Agente Responsável Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3678fe81-48d6-4258-80a7-2be6c8c1ab99",
            "sourceColumn": "_SK Agente Responsável Agidesk",
            "summarizeBy": "sum"
          },
          {
            "name": "_SK Contato Cliente Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91cab1fd-1d75-439a-9d7f-d11c7fd0790c",
            "sourceColumn": "_SK Contato Cliente Agidesk",
            "summarizeBy": "sum"
          },
          {
            "name": "_SK Tarefa Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6361bb2f-7eaf-4471-be6f-824a8e2f098d",
            "sourceColumn": "_SK Tarefa Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Junk Lançamentos Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f88c4531-2310-494c-bf04-eaefbbb907dc",
            "sourceColumn": "_SK Junk Lançamentos Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Data Lançamento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "cd5c79ce-894d-4ce1-a29b-458e6fbb2ae5",
            "sourceColumn": "Data Lançamento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Data Hora Início Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b2cac43b-a515-4284-9810-87382651d61d",
            "sourceColumn": "Data Hora Início Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Data Hora Fim Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "80c8e8c7-c5cf-43be-9876-af43f07c1c86",
            "sourceColumn": "Data Hora Fim Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Conteúdo Lançamento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdd51f7c-51a1-47b4-b621-7ad82d5c3e77",
            "sourceColumn": "Conteúdo Lançamento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Duração Decimal Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "593d42ef-a127-4573-ab0d-5db1efd4de88",
            "sourceColumn": "Duração Decimal Atendimento Agidesk",
            "summarizeBy": "sum"
          },
          {
            "name": "Duração Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isHidden": true,
            "lineageTag": "a03fc6de-b022-4b67-8f1d-0c274bc42c1b",
            "sourceColumn": "Duração Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Data Alteração Atendimento Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7dcdd28c-383d-4966-89bb-c0208ce1016a",
            "sourceColumn": "Data Alteração Atendimento Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "MINUTOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "//PASSO 5: arredonda sem decimais",
              "ROUND(",
              "    //PASSO 3: subtrai, do valor total multiplicado por 100, a parte inteira multiplicada por 100; desta forma, teremos um valor inteiro para a parte decimal (ex: 0.5 = 50; 1.33 = 33; 3.41 = 41)",
              "    (",
              "        //PASSO 1: multiplica por 100 pra pra ter o valor inteiro, sem decimal (ex: 0.5 = 50; 1.33 = 133; 3.41 = 341)",
              "        ('dw fLancamentosAgidesk'[Duração Decimal Atendimento Agidesk] * 100) ",
              "        -",
              "        //PASSO 2: pega a parte inteira do número, e multiplica por 100 (ex: 0.5 = 0; 1.33 = 100; 3.41 = 300)",
              "        (INT('dw fLancamentosAgidesk'[Duração Decimal Atendimento Agidesk]) * 100)",
              "    )",
              "    //PASSO 4: multiplica por 0.60, para transformar de decimal em minutos",
              "    *",
              "    0.60",
              "    ,0",
              ")",
              "",
              "/*",
              "    EXEMPLO COMPLETO:",
              "    Tempo em formato datetime: 00:30:00",
              "    Tempo em formato decimal: 0.5",
              "    PASSO 1: 50",
              "    PASSO 2: 0",
              "    PASSO 3: 50 (50 - 0)",
              "    PASSO 4: 30 (50 * 0.60)",
              "    PASSO 5: 30",
              "",
              "    Tempo em formato datetime: 01:20:00",
              "    Tempo em formato decimal: 1.33",
              "    PASSO 1: 133",
              "    PASSO 2: 100",
              "    PASSO 3: 33 (133 - 100)",
              "    PASSO 4: 19.8 (33 * 0.60)",
              "    PASSO 5: 20",
              "",
              "    Tempo em formato datetime: 03:25:00",
              "    Tempo em formato decimal: 3.41",
              "    PASSO 1: 341",
              "    PASSO 2: 300",
              "    PASSO 3: 41 (341 - 300)",
              "    PASSO 4: 24.6 (41 * 0.60)",
              "    PASSO 5: 25",
              "*/",
              "--Coluna Calculada utilizada na visão de Calendário",
              "--Utilizar junto com a coluna HORAS",
              "--Talita Hübner"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f0cb5a5d-f305-4820-8fe5-ea6384c0a5f3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "HORAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "INT('dw fLancamentosAgidesk'[Duração Decimal Atendimento Agidesk])",
              "--Coluna Calculada utilizada na visão de Calendário",
              "--Utilizar junto com a coluna MINUTOS",
              "--Talita Hübner"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d2a08fa9-c29a-4f8e-8572-b7a3f4b58d56",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "2d27ec61-67c2-4219-9752-bd8a92048dbe",
        "partitions": [
          {
            "name": "dw fLancamentosAgidesk-f951beca-244f-4ffb-866a-d89787739c24",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"srv3hldbs02\\producao\", \"DWBI\"),",
                "    dw_fLancamentosAgidesk = Fonte{[Schema=\"dw\",Item=\"fLancamentosAgidesk\"]}[Data]",
                "in",
                "    dw_fLancamentosAgidesk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dw dQuadroAgidesk",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "_BK Quadro Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b23c1be4-295d-4b51-83a3-03ad95fdfe77",
            "sourceColumn": "_BK Quadro Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "_SK Quadro Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "892d93c6-df29-453b-8546-04bef6da7e58",
            "sourceColumn": "_SK Quadro Agidesk",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição Quadro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6a3d42c-e3e1-4298-bf83-f4e4ff68e8c7",
            "sourceColumn": "Descrição Quadro",
            "summarizeBy": "none"
          },
          {
            "name": "Projeto Agidesk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61eb4f8c-607d-42a9-b37e-5e3b57f64e9d",
            "sourceColumn": "Projeto Agidesk",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ec851013-96d5-4817-a5ef-b8e316c68ba0",
        "partitions": [
          {
            "name": "dw dQuadroAgidesk-1c5a6c8a-063f-448e-979b-394d665690b0",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"SRV3HLDBS02\\producao\", \"DWBI\"),",
                "    dw_dQuadroAgidesk = Fonte{[Schema=\"dw\",Item=\"dQuadroAgidesk\"]}[Data]",
                "in",
                "    dw_dQuadroAgidesk"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dados do Relatório",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date Last Refreshed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "639bd18a-af20-4133-b7a2-0e8a09ba20a4",
            "sourceColumn": "Date Last Refreshed",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "197a23b7-12f1-47b7-868c-d7b22a25fa9c",
        "partitions": [
          {
            "name": "Dados do Relatório-bd7d1177-f41b-40a9-8d0d-b9a539f1e9db",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = #table(type table[Date Last Refreshed=datetime], {{DateTimeZone.SwitchZone(DateTimeZone.FixedUtcNow(),-3,0)}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Date Last Refreshed\", type datetimezone}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "3ddef252-3415-4c9f-bede-5bf449720f8f",
        "measures": [
          {
            "name": "SUM Duração Decimal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Basicas",
            "expression": "SUM('dw fLancamentosAgidesk'[Duração Decimal Atendimento Agidesk])",
            "lineageTag": "89f6cc85-5c41-40cf-9441-acd31dd7c0db"
          },
          {
            "name": "Tamanho Equipe",
            "displayFolder": "Metas",
            "expression": "5",
            "formatString": "0",
            "lineageTag": "fbaeb6e3-b10b-4efc-8eaf-45b22915daf3"
          },
          {
            "name": "Meta Horas Registradas Por Dia",
            "displayFolder": "Metas",
            "expression": "8",
            "formatString": "0",
            "lineageTag": "23160cd6-12c0-404c-a092-7a3764f33e25"
          },
          {
            "name": "Dias Úteis Mês",
            "displayFolder": "Datas",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(dCalendario),",
              "    FILTER(",
              "        ALL(dCalendario),",
              "        --dCalendario[Dia Útil] = \"1\" && dCalendario[Data Referência Produtiva] = [x Data Referencia Ciclo Atual]",
              "        dCalendario[Dia Útil] = \"1\" && dCalendario[Posição Ciclo Produtivo] = \"Presente\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a66ef6d5-6f6b-42e2-8ddd-098ce77d0782"
          },
          {
            "name": "Texto Ciclo Atual",
            "displayFolder": "Textos",
            "expression": [
              "",
              "var ciclo_atual = ",
              "CALCULATE(",
              "    MAX(dCalendario[Ciclo Produtivo]),",
              "    dCalendario[Ciclo Produtivo Seleção] = \"Ciclo Atual\"",
              ")",
              "",
              "Return \"Ciclo Atual: \" & ciclo_atual"
            ],
            "lineageTag": "62bf4d3d-bd48-4222-a4c5-da581743421b"
          },
          {
            "name": "Texto Tamanho Equipe",
            "displayFolder": "Textos",
            "expression": "\"Equipe em \" & [Tamanho Equipe]",
            "lineageTag": "464db4fa-1e6c-4077-a1de-9468031ca122"
          },
          {
            "name": "Meta Horas Registradas Por Ciclo (Equipe)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Metas",
            "expression": "[Tamanho Equipe] * [Meta Horas Registradas Por Dia] * [Dias Úteis Mês]",
            "lineageTag": "44a895da-e2e3-4a2b-b324-7b7b776325cc"
          },
          {
            "name": "Texto Dias Ciclo Produtivo",
            "displayFolder": "Textos",
            "expression": "[Dias Úteis Mês Até Hoje] & \"/\" & [Dias Úteis Mês]",
            "lineageTag": "d405a324-8893-45eb-9ef0-45cf028459bd"
          },
          {
            "name": "Horas Registradas Ciclo Atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dCalendario',",
              "        'dCalendario'[Posição Ciclo Produtivo] = \"Presente\"",
              "    )",
              ")"
            ],
            "lineageTag": "04410790-0a05-458a-be5e-a1b4769fcb56"
          },
          {
            "name": "Meta Horas Registradas Por Ciclo (Equipe) (Blank)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Metas",
            "expression": [
              "IF(ISBLANK([Horas Registradas Ciclo Atual]),BLANK(),[Meta Horas Registradas Por Ciclo (Equipe)])",
              "",
              "// var xDiasUteisCPA = CALCULATE(",
              "//                         COUNTROWS(dCalendario),",
              "//                         FILTER(all(dCalendario),dCalendario[Dia Útil] = \"1\" && dCalendario[Data Referência Produtiva] = [x Data Referencia Ciclo Atual])",
              "//                     )",
              "",
              "// var xHoje = TODAY()",
              "",
              "// var xDiasUteisCPAAteHoje = CALCULATE(",
              "//                             COUNTROWS(dCalendario),",
              "//                             FILTER(all(dCalendario),dCalendario[Dia Útil] = \"1\" && dCalendario[Data Referência Produtiva] = [x Data Referencia Ciclo Atual] && dCalendario[Data] <= xHoje)",
              "//                         )",
              "",
              "// --var xHorasRegistradasCicloAtual = [Hora Registrada Ciclo Atual]",
              "",
              "// --var xRetorno = xDiasUteisCPAAteHoje * 7 * 3.5",
              "// var xRetorno = xDiasUteisCPAAteHoje * 8 * 4.5",
              "",
              "// return if(ISBLANK([Horas Registradas Ciclo Atual]),BLANK(),xRetorno)"
            ],
            "lineageTag": "2c873818-3495-48b0-8051-540d00b12aa2"
          },
          {
            "name": "Meta Percentual Horas Faturadas Por Ciclo",
            "displayFolder": "Metas",
            "expression": "0.90",
            "formatString": "0%;-0%;0%",
            "lineageTag": "19ffb8e5-f330-48b2-a59b-9bd941d3c6c0"
          },
          {
            "name": "Horas Faturadas",
            "displayFolder": "Realizado",
            "expression": [
              "",
              "//cálculo simplificado no ETL (Talita, 16/12/23)",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dw dJunkLancamentosAgidesk',",
              "        'dw dJunkLancamentosAgidesk'[Tipo Faturamento Agidesk] = \"Faturado\"",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "d8ec162e-11aa-44be-a161-26f14022c9d3"
          },
          {
            "name": "Horas Faturadas Ciclo Atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "CALCULATE(",
              "    [Horas Faturadas],",
              "    FILTER(",
              "        'dCalendario',",
              "        'dCalendario'[Posição Ciclo Produtivo] = \"Presente\"",
              "))"
            ],
            "lineageTag": "c6313fd0-0486-450e-a38b-939997d3bc39"
          },
          {
            "name": "% Faturado Ciclo Atual",
            "displayFolder": "Realizado",
            "expression": "DIVIDE([Horas Faturadas Ciclo Atual],[Meta Horas Registradas Por Ciclo (Equipe)],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "bf8fd3ab-cac4-4e39-a08b-38bd1fd64879"
          },
          {
            "name": "Potencial Horas Ciclo Atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Metas",
            "expression": "([Horas Registradas Ciclo Atual] / [Dias Úteis Mês Até Hoje]) * [Dias Úteis Mês]",
            "lineageTag": "aedc8542-bb78-4b0a-81cd-707d9c840d47"
          },
          {
            "name": "Dias Úteis Mês Até Hoje",
            "displayFolder": "Datas",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(dCalendario),",
              "    FILTER(",
              "        ALL(dCalendario),",
              "        dCalendario[Dia Útil] = \"1\" && dCalendario[Posição Ciclo Produtivo] = \"Presente\" && dCalendario[Data] <= TODAY()",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f8dc794f-f2b7-4974-a71e-b53d5710c8a2"
          },
          {
            "name": "% Potencial x Meta Ciclo Atual",
            "displayFolder": "Metas",
            "expression": "DIVIDE([Potencial Horas Ciclo Atual],[Meta Horas Registradas Por Ciclo (Equipe)],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "04acea36-b2f4-4bd9-87a6-a79e22311ccc"
          },
          {
            "name": "Horas Faturadas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": [
              "",
              "-- Horas FATURADAS dos ultimos 12 meses do período financeiro",
              "VAR referencia = ",
              "CALCULATE(",
              "    MAX('dCalendario'[Data Referência Produtiva]),",
              "    FILTER(",
              "        ALL('dCalendario'),",
              "        'dCalendario'[Data] = TODAY()",
              "    )",
              ")",
              "",
              "VAR dataInicial = EDATE(referencia,-1)",
              "VAR data12Meses = EDATE(referencia,-12)",
              "",
              "VAR horas = ",
              "CALCULATE(",
              "    [Horas Faturadas],",
              "    DATESBETWEEN('dCalendario'[Data Referência Produtiva],data12Meses,dataInicial)",
              ")",
              "",
              "RETURN horas"
            ],
            "lineageTag": "01dba5e1-ac14-4e71-95e2-20109445dd15"
          },
          {
            "name": "Horas Abonadas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "//cálculo simplificado no ETL (Talita, 16/12/23)",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dw dJunkLancamentosAgidesk',",
              "        'dw dJunkLancamentosAgidesk'[Tipo Faturamento Agidesk] = \"Abonado\"",
              "    )",
              ")"
            ],
            "lineageTag": "3e3dd0b4-b672-4c61-acc0-dcd58ad4b7a1"
          },
          {
            "name": "Horas Internas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "//cálculo simplificado no ETL (Talita, 16/12/23)",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dw dJunkLancamentosAgidesk',",
              "        'dw dJunkLancamentosAgidesk'[Tipo Faturamento Agidesk] = \"Interno\"",
              "    )",
              ")"
            ],
            "lineageTag": "eaf2fb58-798b-45ce-a383-3ccf9d4be124"
          },
          {
            "name": "Horas Internas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": [
              "",
              "-- Horas INTERNAS dos ultimos 12 meses do período financeiro",
              "VAR referencia = ",
              "CALCULATE(",
              "    MAX('dCalendario'[Data Referência Produtiva]),",
              "    FILTER(",
              "        ALL('dCalendario'),",
              "        'dCalendario'[Data] = TODAY()",
              "    )",
              ")",
              "",
              "VAR dataInicial = EDATE(referencia,-1)",
              "VAR data12Meses = EDATE(referencia,-12)",
              "",
              "VAR horas = ",
              "CALCULATE(",
              "    [Horas Internas],",
              "    DATESBETWEEN('dCalendario'[Data Referência Produtiva],data12Meses,dataInicial)",
              ")",
              "",
              "RETURN horas"
            ],
            "lineageTag": "8026b501-8e73-4aa8-aee9-478eb501e56f"
          },
          {
            "name": "Horas Abonadas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": [
              "",
              "-- Horas ABONADAS dos ultimos 12 meses do período financeiro",
              "VAR referencia = ",
              "CALCULATE(",
              "    MAX('dCalendario'[Data Referência Produtiva]),",
              "    FILTER(",
              "        ALL('dCalendario'),",
              "        'dCalendario'[Data] = TODAY()",
              "    )",
              ")",
              "",
              "VAR dataInicial = EDATE(referencia,-1)",
              "VAR data12Meses = EDATE(referencia,-12)",
              "",
              "VAR horas = ",
              "CALCULATE(",
              "    [Horas Abonadas],",
              "    DATESBETWEEN('dCalendario'[Data Referência Produtiva],data12Meses,dataInicial)",
              ")",
              "",
              "RETURN horas"
            ],
            "lineageTag": "520e81a8-17e3-43c1-a7fd-295ed1c85b4c"
          },
          {
            "name": "% Faturado 12 Meses",
            "displayFolder": "12 Meses",
            "expression": [
              "",
              "IF(",
              "    [Horas Registradas 12 Meses] = 0,",
              "    BLANK(),",
              "    DIVIDE([Horas Faturadas 12 Meses],[Horas Registradas 12 Meses],0)",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6c382ab9-4ca1-4b7c-8851-9b7f2f8e0576"
          },
          {
            "name": "Horas Registradas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": [
              "",
              "-- Horas REGISTRADAS dos ultimos 12 meses do período financeiro",
              "VAR referencia = ",
              "CALCULATE(",
              "    MAX('dCalendario'[Data Referência Produtiva]),",
              "    FILTER(",
              "        ALL('dCalendario'),",
              "        'dCalendario'[Data] = TODAY()",
              "    )",
              ")",
              "",
              "VAR dataInicial = EDATE(referencia,-1)",
              "VAR data12Meses = EDATE(referencia,-12)",
              "",
              "VAR horas = ",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    DATESBETWEEN('dCalendario'[Data Referência Produtiva],data12Meses,dataInicial)",
              ")",
              "",
              "RETURN horas"
            ],
            "lineageTag": "62eae8d6-9d47-4fb3-a01e-541a006b6e62"
          },
          {
            "name": "Meta Horas Faturadas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": "[Horas Registradas 12 Meses] * [Meta Percentual Horas Faturadas Por Ciclo]",
            "lineageTag": "646716c4-5f73-448d-9a18-c2989b3c0a76"
          },
          {
            "name": "Média Horas Registradas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": "DIVIDE([Horas Registradas 12 Meses],12,0)",
            "lineageTag": "840c2647-5c2f-4d01-869c-8e197b0d15a4"
          },
          {
            "name": "Média Horas Faturadas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": "DIVIDE([Horas Faturadas 12 Meses],12,0)",
            "lineageTag": "e28861ce-ff94-4840-8c72-46e4b25c4d67"
          },
          {
            "name": "Média Horas Abonadas 12 Meses",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "12 Meses",
            "expression": "DIVIDE([Horas Abonadas 12 Meses],12,0)",
            "lineageTag": "8c0067b9-d38a-460b-85d8-3dd8f67f9bd5"
          },
          {
            "name": "% Diferença Ano Anterior Ciclo Atual",
            "displayFolder": "Realizado",
            "expression": "[% Faturado Ciclo Atual] - [% Faturado 12 Meses]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "51aff41b-7e71-4aeb-a440-1c2a7a22810d"
          },
          {
            "name": "Meta Horas Registradas Por Ciclo (Analista)",
            "displayFolder": "Metas",
            "expression": "[Meta Horas Registradas Por Dia] * [Dias Úteis Mês]",
            "formatString": "0",
            "lineageTag": "5d63350e-1ba4-4b7d-9b13-c4b7d741cb64"
          },
          {
            "name": "Conteúdo Calendário Analista",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "var dia = SELECTEDVALUE(dCalendario[Dia])",
              "var mes = LOWER(SELECTEDVALUE(dCalendario[Mes Abreviado]))",
              "",
              "return ",
              "dia & \" \" & mes",
              "& UNICHAR(10)",
              "& [String Tempo Analista]"
            ],
            "lineageTag": "cb177bbc-5f33-4380-899e-488628435d39"
          },
          {
            "name": "String Tempo Analista",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "",
              "var horas = [SUM HORAS]",
              "var minutos = [SUM MINUTOS]",
              "var totalHoras = horas + INT(minutos / 60)",
              "var totalMinutos = minutos - (60 * INT(minutos / 60))",
              "",
              "Return",
              "IF(",
              "    horas > 0 || minutos > 0,",
              "",
              "    IF(",
              "        totalHoras >= 0 && totalHoras < 10,",
              "        RIGHT(totalHoras + 100,2),",
              "        totalHoras",
              "    )",
              "    &",
              "    \":\"",
              "    &",
              "    RIGHT(totalMinutos + 100,2)",
              ")"
            ],
            "lineageTag": "97e9e0a1-f6b1-498a-a88b-473fabcdcabe"
          },
          {
            "name": "SUM HORAS",
            "displayFolder": "Calendario",
            "expression": "SUM('dw fLancamentosAgidesk'[HORAS])",
            "lineageTag": "6765fe3c-d7ab-44bb-8664-74305b205db6"
          },
          {
            "name": "SUM MINUTOS",
            "displayFolder": "Calendario",
            "expression": "sum('dw fLancamentosAgidesk'[MINUTOS])",
            "lineageTag": "472633dc-7e7f-4951-ad9d-cf68a22b4f06"
          },
          {
            "name": "Background Calendário Analista",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "var diaSemana = SELECTEDVALUE(dCalendario[Dia Semana])",
              "var data = SELECTEDVALUE(dCalendario[Data])",
              "",
              "var backgroundColor = ",
              "IF(",
              "    data = TODAY(),",
              "    \"#5D00FF76\",",
              "    IF(",
              "        diaSemana in {2,3,4,5,6},",
              "        IF(",
              "            data < TODAY(),",
              "            IF(",
              "                [SUM Duração Decimal] < [Meta Horas Registradas Por Dia],",
              "                \"#6B2328\"",
              "            )",
              "        ),",
              "        \"#666666\"",
              "    )",
              ")",
              "",
              "return backgroundColor"
            ],
            "lineageTag": "6338fedf-33ee-41a3-b742-33e4fffe8d59"
          },
          {
            "name": "Fonte Calendário Analista",
            "displayFolder": "Calendario",
            "expression": "\"#FFFFFF\"",
            "lineageTag": "11c0ac04-fe15-45cb-a80d-99193e021ab3"
          },
          {
            "name": "Meta Horas Faturadas Por Ciclo (Equipe)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Metas",
            "expression": "[Meta Horas Registradas Por Ciclo (Equipe)] * [Meta Percentual Horas Faturadas Por Ciclo]",
            "lineageTag": "b5a45d66-1f16-4e46-8b3f-2be0f751d39c"
          },
          {
            "name": "Texto Horas Analista",
            "displayFolder": "Textos",
            "expression": [
              "",
              "var ciclo = SELECTEDVALUE(dCalendario[Ciclo Produtivo Seleção])",
              "var agente = SELECTEDVALUE('dw dAgenteAgidesk'[Analista])",
              "var metaOntem = IF(agente = \"Talita\", [Meta Horas Registradas Ontem (Analista)]/2, [Meta Horas Registradas Ontem (Analista)])",
              "var metaCiclo = IF(agente = \"Talita\", [Meta Horas Registradas Por Ciclo (Analista)]/2, [Meta Horas Registradas Por Ciclo (Analista)])",
              "",
              "var texto = [SUM Duração Decimal] & \" horas registradas de \" & ",
              "IF(",
              "     ciclo = \"Ciclo Atual\",",
              "     metaOntem & \" possíveis até ontem\",",
              "     metaCiclo & \" possíveis\"",
              ")",
              "",
              "return texto"
            ],
            "lineageTag": "dcc7f6ca-009d-409b-b7ea-4764cd2cb474"
          },
          {
            "name": "Meta Horas Registradas Ontem (Analista)",
            "displayFolder": "Metas",
            "expression": "([Dias Úteis Mês Até Hoje] - 1) * [Meta Horas Registradas Por Dia]",
            "formatString": "0.00",
            "lineageTag": "830421c6-79bb-45a3-a9bc-43db347a3b15"
          },
          {
            "name": "Diferença Meta x Registrado Hoje",
            "displayFolder": "Realizado",
            "expression": "[Meta Horas Registradas Ontem] - [Horas Registradas Ciclo Atual]",
            "lineageTag": "daa88c98-03cc-4b6b-bc42-05ecb598a0e6"
          },
          {
            "name": "Meta Horas Registradas Ontem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Metas",
            "expression": "([Dias Úteis Mês Até Hoje] - 1) * [Tamanho Equipe] * [Meta Horas Registradas Por Dia]",
            "formatString": "0",
            "lineageTag": "2f2722be-5492-451d-96b4-ce28ecef1c58"
          },
          {
            "name": "Horas Abonadas (zero)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": "IF(ISBLANK([Horas Abonadas]),0,[Horas Abonadas])",
            "lineageTag": "8a21027c-ccb8-49eb-9b37-6c89d5a57ca1"
          },
          {
            "name": "% Faturado",
            "displayFolder": "Realizado",
            "expression": "DIVIDE([Horas Faturadas],[Meta Horas Registradas Por Ciclo (Equipe)],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5fe38e21-fbc0-4fa1-90fa-5ffb55c8d686"
          },
          {
            "name": "Meta Horas Faturadas Ontem",
            "displayFolder": "Metas",
            "expression": "[Meta Horas Registradas Ontem] * [Meta Percentual Horas Faturadas Por Ciclo]",
            "formatString": "0",
            "lineageTag": "0fa1ccc8-c837-4109-9041-00e5addf73d1"
          },
          {
            "name": "COUNT Tarefas",
            "displayFolder": "Basicas",
            "expression": "DISTINCTCOUNT('dw fLancamentosAgidesk'[_SK Tarefa Agidesk])",
            "formatString": "0",
            "lineageTag": "0a1e16bb-311f-4083-aba1-e73d16b90b4e"
          },
          {
            "name": "Horas Internas (zero)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": "IF(ISBLANK([Horas Internas]),0,[Horas Internas])",
            "lineageTag": "6bd9368c-f8af-4be5-b7b8-dc37ca9e3a3e"
          },
          {
            "name": "Horas Ajuste",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dw dJunkLancamentosAgidesk',",
              "        'dw dJunkLancamentosAgidesk'[Tipo Lançamento Agidesk] = \"Ajuste\"",
              "    )",
              ")"
            ],
            "lineageTag": "bf3a980c-d28e-4cc6-9bca-20a3f8673f1e"
          },
          {
            "name": "Horas Produção",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Realizado",
            "expression": [
              "",
              "CALCULATE(",
              "    [SUM Duração Decimal],",
              "    FILTER(",
              "        'dw dJunkLancamentosAgidesk',",
              "        'dw dJunkLancamentosAgidesk'[Tipo Lançamento Agidesk] <> \"Ajuste\" && 'dw dJunkLancamentosAgidesk'[Tipo Lançamento Agidesk] <> \"Treinamento\"",
              "    )",
              ")"
            ],
            "lineageTag": "9697f6d0-23f1-4aae-87b6-0697ce52e354"
          },
          {
            "name": "Horas Faturadas Projeto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    MAX('dw dProjetoAgidesk'[Recorrêcia]) = \"Única\",",
              "    CALCULATE(",
              "        [Horas Faturadas],",
              "        ALL(dCalendario)",
              "    )",
              "    ,",
              "    [Horas Faturadas]",
              ")"
            ],
            "lineageTag": "cc105d25-4090-444e-8623-0882b4fc3c4c"
          },
          {
            "name": "Horas Totais Projeto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(HorasProjetos[Horas])",
            "lineageTag": "4344e492-3248-4e2f-b31a-4a79a131dcdb"
          },
          {
            "name": "Horas Restantes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Horas Totais Projeto] - [Horas Faturadas Projeto]",
            "lineageTag": "bb4c9368-da40-464d-9651-9b326ac86b9e"
          },
          {
            "name": "Horas Registradas Projeto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    MAX('dw dProjetoAgidesk'[Recorrêcia]) = \"Única\",",
              "    CALCULATE(",
              "        [SUM Duração Decimal],",
              "        ALL(dCalendario)",
              "    )",
              "    ,",
              "    [SUM Duração Decimal]",
              ")"
            ],
            "lineageTag": "54745915-1018-4583-bca1-ec48ae9205cd"
          },
          {
            "name": "Horas Abonadas Projeto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    MAX('dw dProjetoAgidesk'[Recorrêcia]) = \"Única\",",
              "    CALCULATE(",
              "        [Horas Abonadas (zero)],",
              "        ALL(dCalendario)",
              "    )",
              "    ,",
              "    [Horas Abonadas (zero)]",
              ")"
            ],
            "lineageTag": "ddfdbb65-5d81-4e37-99c7-c37486b3b001"
          },
          {
            "name": "Dias Úteis Restantes",
            "displayFolder": "Datas",
            "expression": "[Dias Úteis Mês] - [Dias Úteis Mês Até Hoje]",
            "formatString": "0",
            "lineageTag": "c4d902eb-abf9-4f3a-ae97-d57c1f6fa782"
          },
          {
            "name": "Média Diária Horas Restantes",
            "expression": "IF([Horas Restantes] <= 0, 0, [Horas Restantes] / ([Dias Úteis Restantes] + 1))",
            "formatString": "0.00",
            "lineageTag": "15c6b18a-5131-47ef-be6d-ba00c95237b7"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LancamentosDetalhados",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "914d3e6f2fa84be0b306505f37cbb233"
          }
        ],
        "columns": [
          {
            "name": "LancamentosDetalhados",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6be1ac97-92ae-41e8-bec7-e7f20e5db831",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "LancamentosDetalhados Campos"
                }
              ]
            },
            "sortByColumn": "LancamentosDetalhados Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LancamentosDetalhados Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0585b8c8-567a-46e5-a559-1819d5b526d2",
            "sortByColumn": "LancamentosDetalhados Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "LancamentosDetalhados Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4f224f3c-4915-4db3-8dbb-489c3b866532",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "bad5ce6a-1b9b-44e7-bce6-3072a77ec589",
        "partitions": [
          {
            "name": "LancamentosDetalhados",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Cliente\", NAMEOF('dw dClienteAgidesk'[Descrição Cliente Agidesk]), 0),",
                "    (\"Projeto\", NAMEOF('dw dProjetoAgidesk'[Nome Projeto Agidesk]), 1),",
                "    (\"Quadro\", NAMEOF('dw dQuadroAgidesk'[Descrição Quadro]), 2),",
                "    (\"Chamado\", NAMEOF('dw dTarefaAgidesk'[_BK Tarefa Agidesk]), 3),",
                "    (\"Tarefa\", NAMEOF('dw dTarefaAgidesk'[Título Tarefa Agidesk]), 4),",
                "    (\"Time Atendimento\", NAMEOF('dw dJunkLancamentosAgidesk'[Time Atendimento Agidesk]), 5),",
                "    (\"Analista\", NAMEOF('dw dAgenteAgidesk'[Analista]), 6),",
                "    (\"Tipo Lançamento\", NAMEOF('dw dJunkLancamentosAgidesk'[Tipo Lançamento Agidesk]), 7),",
                "    (\"Tipo Faturamento\", NAMEOF('dw dJunkLancamentosAgidesk'[Tipo Faturamento Agidesk]), 8),",
                "    (\"Conteúdo Lançamento\", NAMEOF('dw fLancamentosAgidesk'[Conteúdo Lançamento Agidesk]), 9),",
                "    (\"Início Atendimento\", NAMEOF('dw fLancamentosAgidesk'[Data Hora Início Atendimento Agidesk]), 10),",
                "    (\"Fim Atendimento\", NAMEOF('dw fLancamentosAgidesk'[Data Hora Fim Atendimento Agidesk]), 11),",
                "    (\"Horas Registradas\", NAMEOF('Medidas'[SUM Duração Decimal]), 12)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PlanejamentoAlocacao",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "492b0596-942b-4c4e-9aaa-7429a108b4cc",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Projeto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4212c92-34b0-46a4-a60d-131408549a68",
            "sourceColumn": "Projeto",
            "summarizeBy": "none"
          },
          {
            "name": "Papel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5593a9fe-3995-463d-8708-0c4876030471",
            "sourceColumn": "Papel",
            "summarizeBy": "none"
          },
          {
            "name": "Pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d4084bc-ca99-46b8-b94f-8e05fc57e843",
            "sourceColumn": "Pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Serviço",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23960a97-ef1b-441a-9562-5b5efc4572ac",
            "sourceColumn": "Tipo Serviço",
            "summarizeBy": "none"
          },
          {
            "name": "Atribuição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56e1b256-eb42-4333-ab42-5df5840a6e38",
            "sourceColumn": "Atribuição",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "11b113b2-e63b-4be6-a831-6a0417502b6e",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Horas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d4d4a99-191f-4d1f-9a42-81c8cf18e1d5",
            "sourceColumn": "Horas",
            "summarizeBy": "sum"
          },
          {
            "name": "Dias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "69e0f599-6948-4314-8745-a61d2a215b5b",
            "sourceColumn": "Dias",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Horas Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71773fe6-8310-42d3-a5ae-bf5f473f717e",
            "sourceColumn": "Total Horas Semana",
            "summarizeBy": "sum"
          },
          {
            "name": "Semanas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cdadc241-9a37-467a-bc86-3084be75b448",
            "sourceColumn": "Semanas",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Horas Mensais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b32a1a4f-6618-483d-bbc5-8d13f0c12855",
            "sourceColumn": "Total Horas Mensais",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0e83cde2-76a6-4baf-b7e5-f3eeede20c22",
        "partitions": [
          {
            "name": "PlanejamentoAlocacao",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Files(\"https://tresh.sharepoint.com/sites/RowUpOperao-Planejamento\", [ApiVersion = 15]),",
                "    #\"Alocação xlsx_https://tresh sharepoint com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\" = Fonte{[Name=\"Alocação.xlsx\",#\"Folder Path\"=\"https://tresh.sharepoint.com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Alocação xlsx_https://tresh sharepoint com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\"),",
                "    TabelaPlanejamentoMensal_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"TabelaPlanejamentoMensal\",Kind=\"Table\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(TabelaPlanejamentoMensal_Table,{\"Observação\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "HorasProjetos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21609185-0df9-46be-9b1f-e4df14439ded",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Projeto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f188ff09-24ef-4800-8d87-0f9b1ea25095",
            "sourceColumn": "Projeto",
            "summarizeBy": "none"
          },
          {
            "name": "Horas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5bbf8b1c-5213-472f-ad70-2a8ef8d8de92",
            "sourceColumn": "Horas",
            "summarizeBy": "sum"
          },
          {
            "name": "Recorrêcia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "780269a8-586b-4490-8611-0bd206bd3482",
            "sourceColumn": "Recorrêcia",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d3e91910-32e7-4b6f-a59d-32db19dd102f",
        "partitions": [
          {
            "name": "HorasProjetos",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Files(\"https://tresh.sharepoint.com/sites/RowUpOperao-Planejamento\", [ApiVersion = 15]),",
                "    #\"Projetos xlsx_https://tresh sharepoint com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\" = Fonte{[Name=\"Projetos.xlsx\",#\"Folder Path\"=\"https://tresh.sharepoint.com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Projetos xlsx_https://tresh sharepoint com/sites/RowUpOperao-Planejamento/Documentos Compartilhados/Planejamento/\"),",
                "    TabelaProjetos_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"TabelaProjetos\",Kind=\"Table\"]}[Data]",
                "in",
                "    TabelaProjetos_Table"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}